#!/bin/sh

EVENTS_HEADER="$1"

(
	cat <<- EOF
	#define __SCRIBE_EVENT(name, ...) name
	EOF
	cat $EVENTS_HEADER
) | gcc -E -x c - | grep ^scribe_event | sed 's/\(.*\)/\1 \U\1/' |
(
	echo "/* This file is automatically generated. Do not edit. */"
	echo "#ifndef _LINUX_SCRIBE_DEFINES_H_"
	echo "#define _LINUX_SCRIBE_DEFINES_H_"
	while read line; do
		set -- $line
		LNAME=$1
		UNAME=$2
		echo "#define upper$LNAME $UNAME"
		echo "#define struct$UNAME struct $LNAME"
	done
	echo "#endif"
)
