#
# Makefile for scribe, the record/replay mechanism
#

obj-$(CONFIG_SCRIBE) += scribe.o resource/

scribe-y := context.o device.o main.o event.o syscalls.o uaccess.o backtrace.o \
	    memory.o pump.o bookmark.o socket.o
